from enum import Enum


class NFType(Enum):
    NRF = "NRF"
    UDM = "UDM"
    AMF = "AMF"
    SMF = "SMF"
    AUSF = "AUSF"
    NEF = "NEF"
    PCF = "PCF"
    SMSF = "SMSF"
    NSSF = "NSSF"
    UDR = "UDR"
    LMF = "LMF"
    GMLC = "GMLC"
    FIVEG_EIR = "5G_EIR"
    SPP = "SEPP"
    UPF = "UPF"
    N3IWF = "N3IWF"
    AF = "AF"
    UDSF = "UDSF"
    BSF = "BSF"
    CHF = "CHF"
    NWDAF = "NWDAF"
