from enum import Enum


class ServiceName(str, Enum):
    nnrf_nfm = "nnrf_nfm-nfm"
    nnrf_disc = "nnrf_nfm-disc"
    nudem_sdm = "nudm-sdm"
    nudm_uecm = "nudm-uecm"
    nudm_ueau = "nudm-ueau"
    nudm_ee = "nudm-ee"
    nudm_pp = "nudm-pp"
    nafm_comm = "namf-comm"
    nafm_evts = "namf-evts"
    namf_mt = "namf-mt"
    namf_loc = "namf-loc"
    nsmf_pdusession = "nsmf-pdusession"
    nsmf_event_exposure = "nsmf-event-exposure"
    nausf_auth = "nausf-auth"
    nausf_sorprotection = "nausf-sorprotection"
    nausf_upuprotection = "nausf-upuprotection"
    nnef_pfdmanagement = "nnef-pfdmanagement"
    npcf_am_policy_control = "npcf-am-policy-control"
    npcf_smpolicycontrol = "npcf-smpolicycontrol"
    npcf_policyauthorization = "npcf-policyauthorization"
    npcf_bdtpolicycontrol = "npcf-bdtpolicycontrol"
    npcf_eventexposure = "npcf-eventexposure"
    npcf_ue_policy_control = "npcf-ue-policy-control"
    nsmsf_sms = "nsmsf-sms"
    nnssf_nssselection = "nnssf-nsselection"
    nnssf_nssaiavailability = "nnssf-nssaiavailability"
    nudr_dr = "nudr-dr"
    nlmf_loc = "nlmf-loc"
    n5g_eir_eic = "n5g-eir-eic"
    nbsf_management = "nbsf-management"
    nchf_spendinglimitcontorl = "nchf-spendinglimitcontrol"
    nchf_convergedcharging = "nchf-convergedcharging"
    nnwdaf_eventssubscription = "nnwdaf-eventssubscription"
    nnwdaf_analyticsinfo = "nnwdaf-analyticsinfo"
