openapi: 3.0.0
info:
    description: NRF Service
    title: NRF Service
servers:
- url: '/'
paths:
    # NRF Discovery
    /discovery:
        get:
            operationId: SearchNFInstances
            responses:
                200:
                    description: Expected response to a valid request
                307:
                    description: Temporary Redirect
                400:
                    description: Bad request
                403:
                    description: Forbidden
                404:
                    description: Not Found
                411:
                    description: Length Required
                413:
                    description: Payload Too Large
                415:
                    description: Unsupported Media Type
                500:
                    description: Internal Server Error
                501:
                    description: Not Implemented
                503:
                    description: Service Unavailable
                default:
                    description: Generic Error
            summary: Search a collection of NF Instances
            tags:
                - NF Discovery Instances (Store)
    
    # NRF AccessToken
    /oauth2/token:
        post:
            operationId: AccessTokenRequest
            requestBody:
                required: true
            responses:
                200:
                    description: Successful Access Token Request
                400:
                    description: Error in the Access Token Request
            summary: Access Token Request
            tags:
            - Access Token Request
    
    # NRF Management
    /nf-instances:
        get:
            operationId: GetNFInstances
            parameters:
            - description: Type of NF
              explode: true
              in: query
              name: nf-type
              required: false
              style: form
            - description: How many items to return at one time
              explode: true
              in: query
              name: limit
              required: false
              schema:
                format: int32
                type: integer
              style: form
            responses:
                200:
                    content:
                        application/3gppHal+json:
                            schema:
                                minProperties: 1
                                properties:
                                    _links:
                                        description: List of the URI of NF instances. It has two members whose names are item and self. The item one contains an array of URIs.
                                        type: object
                                    type: object
                    description: Expected response to a valid request
                400:
                    description: Bad request
                403:
                    description: Forbidden
                404:
                    description: Not Found
                411:
                    description: Length Required
                413:
                    description: Payload Too Large
                415:
                    description: Unsupported Media Type
                500:
                    description: Internal Server Error
                501:
                    description: Not Implemented
                503:
                    description: Service Unavailable
                default:
                    description: Generic Error
            summary: Retrieves a collection of NF Instances
            tags:
            - NF Instances (Store)
    
    /nf-instances/{nfInstanceID}:
        delete:
            operationId: DeregisterNFInstance
            parameters:
                - description: Unique ID of the NF Instance to deregister
                  explode: false
                  in: path
                  name: nfInstanceID
                  required: true
                  style: simple
            responses:
                204:
                    description: Expected response to a successful deregistration
            summary: Deregisters a given NF Instance
            tags:
            - NF Instance ID (Document)
        get:
            operationId: GetNFInstance
            parameters:
            - description: Unique ID of the NF Instance
              explode: false
              in: path
              name: nfInstanceID
              required: true
              style: simple
            responses:
                200:
                    description: Expected response to a valid request
                400:
                    description: Bad request
                403:
                    description: Forbidden
                404:
                    description: Not Found
                411:
                    description: Length Required
                413:
                    description: Payload Too Large
                415:
                    description: Unsupported Media Type
                500:
                    description: Internal Server Error
                501:
                    description: Not Implemented
                503:
                    description: Service Unavailable
                default:
                    description: Generic Error
            summary: Read the profile of a given NF Instance
            tags:
            - NF Instance ID (Document)
        patch:
            operationId: UpdateNFInstance
            parameters:
            - description: Unique ID of the NF Instance to update
              explode: false
              in: path
              name: nfInstanceID
              required: true
              style: simple
            requestBody:
                content:
                    application/json-patch+json:
                        schema:
                            minItems: 1
                            type: array
                required: true
            responses:
                200:
                    description: Expected response to a valid request
                204:
                    description: Expected response with empty body
                400:
                    description: Bad request
                403:
                    description: Forbidden
                404:
                    description: Not Found
                411:
                    description: Length Required
                413:
                    description: Payload Too Large
                415:
                    description: Unsupported Media Type
                500:
                    description: Internal Server Error
                501:
                    description: Not Implemented
                503:
                    description: Service Unavailable
                default:
                    description: Generic Error
            summary: Update NF Instance profile
            tags:
            - NF Instance ID (Document)
        put:
            operationId: RegisterNFInstance
            parameters:
            - description: Unique ID of the NF Instance to register
              explode: false
              in: path
              name: nfInstanceID
              required: true
              style: simple
            requestBody:
                required: true
            responses:
                200:
                    description: OK (Profile Replacement)
                201:
                    description: Expected response to a valid request
                400:
                    description: Bad request
                403:
                    description: Forbidden
                404:
                    description: Not Found
                411:
                    description: Length Required
                413:
                    description: Payload Too Large
                415:
                    description: Unsupported Media Type
                500:
                    description: Internal Server Error
                501:
                    description: Not Implemented
                503:
                    description: Service Unavailable
                default:
                    description: Generic Error
            summary: Register a new NF Instance
            tags:
            - NF Instance ID (Document)

    /subscriptions:
        post:
            callbacks:
                onNFStatusEvent:
                    '{$request.body#/nfStatusNotificationUri}':
                        post:
                            operationId: onNFStatusEvent_Post
                            requestBody:
                                description: Notification Payload
                            responses:
                                204:
                                    description: Expected response to a successful callback processing
                                400:
                                    description: Bad request
                                403:
                                    description: Forbidden
                                404:
                                    description: Not Found
                                411:
                                    description: Length Required
                                413:
                                    description: Payload Too Large
                                415:
                                    description: Unsupported Media Type
                                500:
                                    description: Internal Server Error
                                501:
                                    description: Not Implemented
                                503:
                                    description: Service Unavailable
                                default:
                                    description: Generic Error
                            x-callback-request: true
            operationId: CreateSubscription
            requestBody:
                required: true
            responses:
                201:
                    description: Expected response to a valid request
                400:
                    description: Bad request
                403:
                    description: Forbidden
                404:
                    description: Not Found
                411:
                    description: Length Required
                413:
                    description: Payload Too Large
                415:
                    description: Unsupported Media Type
                500:
                    description: Internal Server Error
                501:
                    description: Not Implemented
                503:
                    description: Service Unavailable
                default:
                    description: Generic Error
            summary: Create a new subscription
            tags:
            - Subscriptions (Collection)

    /subscriptions/{subscriptionID}:
        delete:
            operationId: RemoveSubscription
            parameters:
            - description: Unique ID of the subscription to remove
              explode: false
              in: path
              name: subscriptionID
              required: true
              schema:
              pattern: ^([0-9]{5,6}-)?[^-]+$
              type: string
              style: simple
            responses:
                204:
                    description: Expected response to a successful subscription removal
                400:
                    description: Bad request
                403:
                    description: Forbidden
                404:
                    description: Not Found
                411:
                    description: Length Required
                413:
                    description: Payload Too Large
                415:
                    description: Unsupported Media Type
                500:
                    description: Internal Server Error
                501:
                    description: Not Implemented
                503:
                    description: Service Unavailable
                default:
                    description: Generic Error
            summary: Deletes a subscription
            tags:
            - Subscription ID (Document)
        patch:
            operationId: UpdateSubscription
            parameters:
                - description: Unique ID of the subscription to update
                  explode: false
                  in: path
                  name: subscriptionID
                  required: true
                  schema:
                    pattern: ^([0-9]{5,6}-)?[^-]+$
                    type: string
                  style: simple
            requestBody:
                content:
                    application/json-patch+json:
                        schema:
                            type: array
                required: true
            responses:
                200:
                    description: Expected response to a valid request
                204:
                    description: No Content
                400:
                    description: Bad request
                403:
                    description: Forbidden
                404:
                    description: Not Found
                411:
                    description: Length Required
                413:
                    description: Payload Too Large
                415:
                    description: Unsupported Media Type
                500:
                    description: Internal Server Error
                501:
                    description: Not Implemented
                503:
                    description: Service Unavailable
                default:
                    description: Generic Error
            summary: Updates a subscription
            tags:
            - Subscription ID (Document)

components:
    headers:
        cache-control:
            explode: false
            required: true
            schema:
                enum:
                - no-store
                type: string
            style: simple
        pragma:
            explode: false
            required: true
            schema:
                enum:
                - no-cache
                type: string
            style: simple
    schemas:
        NFType:
            enum:
            - NRF
            - UDM
            - AMF
            - SMF
            - AUSF
            - NEF
            - PCF
            - SMSF
            - NSSF
            - UDR
            - LMF
            - GMLC
            - 5G_EIR
            - SEPP
            - UPF
            - N3IWF
            - AF
            - UDSF
            - BSF
            - CHF
            - NWDAF
            type: string

